#!/bin/bash

PACKAGES="
	sys-kernel/linux-headers
	sys-libs/glibc
	sys-libs/uclibc
	sys-devel/gcc
	sys-devel/binutils
	dev-libs/ppl
	dev-libs/cloog-ppl
	dev-libs/gmp
	dev-libs/mpfr
	sys-libs/glibc
	sys-libs/uclibc
	sys-devel/gcc
	sys-devel/binutils
	sys-libs/glibc
	sys-libs/uclibc
	sys-devel/gcc
	sys-devel/binutils
	dev-libs/glib
	dev-libs/klibc"

if [[ $USER != root ]]; then
	echo "Please run this script as root!"
	exit
fi

print_help() {
	echo "rebuild-all [-i] [-m|--minimal] [-s|--show] [-h|--help] [emerge opts...]"
}

emerge_opts=""

until [ -z "$1" ]; do
	case $1 in
		-h | --help )
			print_help
			exit
			;;
		-i )
			_opts="--ignore-default-opts"
			;;
		-m | --minimal )
			_minimal="true"
			;;
		-s | --show )
			_show_list="true"
			;;
		* )
			emerge_opts="$emerge_opts $1"
			;;
	esac
	shift
done

_2emerge=""

for _pack in ${PACKAGES}; do
	eix -q -I ${_pack} && _2emerge="${_2emerge} ${_pack}"
done

[[ -f /var/log/rebuild.log ]] && mv /var/log/rebuild.log{,.old}

if [[ ${_show_list} == "true" ]]; then
	/lib64/rc/bin/einfo "This will be emerged ..."
	emerge -p ${_2emerge} ${emerge_opts}
fi

for i in ${PACKAGES}; do
	if eix -q -I ${i}; then
		emerge -1v ${_opts} $i ${emerge_opts} || exit
		source /etc/profile
		echo "$i done" >> /var/log/rebuild.log
	fi
done

if [[ ${_minimal} != "true" ]]; then
	emerge -1vt ${_opts} system ${emerge_opts}
	emerge -1vt ${_opts} world ${emerge_opts}
fi
