#!/bin/bash

. /lib/gentoo/functions.sh

if type -p nproc > /dev/null; then
	NUMPROC=$(nproc)
else
	NUMPROC=1
fi

for overlay in $(portageq get_repos /); do
	ebegin "Creating metadata-cache for ${overlay} ..."
		egencache --jobs=${NUMPROC} --repo=${overlay} --update
	eend $?
	ebegin "Generating local USE desc"
		egencache --jobs=${NUMPROC} --repo=${overlay} --update --update-use-local-desc
	eend $?
done
