#!/bin/sh
source /etc/conf.d/cgroup-helper

rmdir ${CGROUP_MOUNTPOINT}/$*
[[ -d ${CGROUP_MOUNTPOINT}/user ]] || mkdir ${CGROUP_MOUNTPOINT}/user
[[ -d ${CGROUP_MOUNTPOINT}/user ]] && chmod 0777 ${CGROUP_MOUNTPOINT}/user
